Use Revenue_leakages_db;
SELECT ROUND(SUM(REVENUE),2) AS TOTAL_REVENUE FROM REVENUE_TRANSACTIONS;
SELECT ROUND(SUM(PROFIT),2) AS TOTAL_PROFIT FROM REVENUE_TRANSACTIONS;
SELECT ROUND(SUM(RETURNCOST),2) AS REVENUE_LOST_RETURNS FROM REVENUE_TRANSACTIONS;
SELECT ROUND(SUM(REVENUE*DISCOUNTPCT/100),2) AS REVENUE_LOST_DISCOUNTS FROM REVENUE_TRANSACTIONS;