Use revenue_leakages_db;
SELECT CATEGORY, ROUND(SUM(REVENUE * DISCOUNTPCT/100),2) AS DISCOUNT_LEAKAGE FROM REVENUE_TRANSACTIONS GROUP BY CATEGORY ORDER BY DISCOUNT_LEAKAGE DESC;
SELECT CATEGORY, ROUND(SUM(RETURNCOST),2) AS RETURN_LEAKAGE FROM REVENUE_TRANSACTIONS GROUP BY CATEGORY ORDER BY RETURN_LEAKAGE DESC;
SELECT REGION, ROUND(SUM(REVENUE * DISCOUNTPCT/100),2) AS DISCOUNT_LEAKAGE FROM REVENUE_TRANSACTIONS GROUP BY REGION ORDER BY DISCOUNT_LEAKAGE DESC;
SELECT REGION, ROUND(SUM(RETURNCOST),2) AS RETURN_LEAKAGE FROM REVENUE_TRANSACTIONS GROUP BY REGION ORDER BY RETURN_LEAKAGE DESC;

