USE REVENUE_LEAKAGES_DB;
SELECT REGION, ROUND(SUM(REVENUE),2) AS REVENUE FROM REVENUE_TRANSACTIONS GROUP BY REGION ORDER BY REVENUE DESC;
SELECT REGION, ROUND(SUM(PROFIT),2) AS PROFIT FROM REVENUE_TRANSACTIONS GROUP BY REGION ORDER BY PROFIT DESC;
SELECT CATEGORY, ROUND(SUM(REVENUE),2) AS REVENUE, ROUND(SUM(PROFIT),2) AS PROFIT FROM REVENUE_TRANSACTIONS GROUP BY CATEGORY ORDER BY PROFIT DESC;